ARDUINO_LIBS = ds3231-master wire SoftwareSerial HMC5883L Low-Power-master DHT-sensor-library-master BMP180_Breakout_Arduino_Library-master
#BOARD_TAG    = pro
#BOARD_TAG    = AVR_PRO
#BOARD_TAG    = pro3v328
MCU = atmega328p
F_CPU = 8000000L
VARIANT = eightanaloginputs
include $(ARDMK_DIR)/Arduino.mk

